/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Box;
import persistencia.ConexaoBanco;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        liberaPermissao();
        
    }
    TelaLogin telalogin = new TelaLogin();
    ConexaoBanco conect = new ConexaoBanco();
    
    public final void liberaPermissao() {
        switch (telalogin.tipouser) {
            case "ALUNO":
                jmCadastro.setVisible(false);
                jmManutencao.setVisible(false);
                jmRelatorio.setVisible(false);
                break;

            case "PROFESSOR":
               jmCadastro.setVisible(false);
               jmManutencao.setVisible(false);
               break;

            case "ADMINISTRADOR":
                break;

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify tis code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmCadAutor = new javax.swing.JMenuItem();
        jmCadCategoria = new javax.swing.JMenuItem();
        jmCadCidade = new javax.swing.JMenuItem();
        jmCadDepartamento = new javax.swing.JMenuItem();
        jmCadEditora = new javax.swing.JMenuItem();
        jmCadFornecedor = new javax.swing.JMenuItem();
        jmCadFuncionario = new javax.swing.JMenuItem();
        jmCadObra = new javax.swing.JMenuItem();
        jmCadUsuario = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jjRelatAutor = new javax.swing.JMenuItem();
        jjRelatCategoria = new javax.swing.JMenuItem();
        jjRelatCidade = new javax.swing.JMenuItem();
        jjRelatDepartamento = new javax.swing.JMenuItem();
        jRelatEditora = new javax.swing.JMenuItem();
        jjRelaEmprestimo = new javax.swing.JMenuItem();
        jjRelatFornecedor = new javax.swing.JMenuItem();
        jjRelatFuncionario = new javax.swing.JMenuItem();
        jjRelatObra = new javax.swing.JMenuItem();
        jRelatUsuario = new javax.swing.JMenuItem();
        jmFuncionalidades = new javax.swing.JMenu();
        jEmprestar = new javax.swing.JMenuItem();
        jDevolver = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManAutor = new javax.swing.JMenuItem();
        jmiManCategoria = new javax.swing.JMenuItem();
        jmiManCidade = new javax.swing.JMenuItem();
        jmiManDepartamento = new javax.swing.JMenuItem();
        jmiManEditora = new javax.swing.JMenuItem();
        jmiManFornecedor = new javax.swing.JMenuItem();
        jmiManFuncionario = new javax.swing.JMenuItem();
        jmiManObra = new javax.swing.JMenuItem();
        jmiManUsuario = new javax.swing.JMenuItem();
        jTrocarusuario = new javax.swing.JMenu();
        menuUsuario = new javax.swing.JMenuItem();
        submenuAlterarSenha = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");
        setMinimumSize(new java.awt.Dimension(300, 300));

        jAreaTrabalho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema de Biblioteca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Olá "+telalogin.nomelogado+" - "+telalogin.matriculalogado);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/userlogado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jAreaTrabalho.add(jPanel1);
        jPanel1.setBounds(0, 290, 410, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/BIBLIOTECA.jpg"))); // NOI18N
        jAreaTrabalho.add(jLabel1);
        jLabel1.setBounds(0, 40, 1000, 460);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sistema de Biblioteca");
        jAreaTrabalho.add(jLabel5);
        jLabel5.setBounds(10, 10, 170, 30);

        jmbMenuPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmbMenuPrincipal.setPreferredSize(new java.awt.Dimension(157, 30));

        jmCadastro.setText("Cadastro");

        jmCadAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmCadAutor.setText("Autor");
        jmCadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadAutorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadAutor);

        jmCadCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmCadCategoria.setText("Categoria");
        jmCadCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadCategoriaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadCategoria);

        jmCadCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmCadCidade.setText("Cidade");
        jmCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadCidadeActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadCidade);

        jmCadDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmCadDepartamento.setText("Departamento");
        jmCadDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadDepartamentoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadDepartamento);

        jmCadEditora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmCadEditora.setText("Editora");
        jmCadEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadEditoraActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadEditora);

        jmCadFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmCadFornecedor.setText("Fornecedor");
        jmCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadFornecedorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadFornecedor);

        jmCadFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jmCadFuncionario.setText("Funcionário");
        jmCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadFuncionario);

        jmCadObra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmCadObra.setText("Livro");
        jmCadObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadObraActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadObra);

        jmCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmCadUsuario.setText("Usuário");
        jmCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadUsuarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmCadUsuario);

        jmbMenuPrincipal.add(jmCadastro);

        jmRelatorio.setText("Relatórios");

        jjRelatAutor.setText("Autor");
        jjRelatAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatAutorActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatAutor);

        jjRelatCategoria.setText("Categoria");
        jjRelatCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatCategoriaActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatCategoria);

        jjRelatCidade.setText("Cidade");
        jjRelatCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatCidadeActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatCidade);

        jjRelatDepartamento.setText("Departamento");
        jjRelatDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatDepartamentoActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatDepartamento);

        jRelatEditora.setText("Editora");
        jRelatEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatEditoraActionPerformed(evt);
            }
        });
        jmRelatorio.add(jRelatEditora);

        jjRelaEmprestimo.setText("Empréstimo");
        jjRelaEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelaEmprestimoActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelaEmprestimo);

        jjRelatFornecedor.setText("Fornecedor");
        jjRelatFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatFornecedorActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatFornecedor);

        jjRelatFuncionario.setText("Funcionário");
        jjRelatFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatFuncionarioActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatFuncionario);

        jjRelatObra.setText("Livro");
        jjRelatObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjRelatObraActionPerformed(evt);
            }
        });
        jmRelatorio.add(jjRelatObra);

        jRelatUsuario.setText("Usuário");
        jRelatUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatUsuarioActionPerformed(evt);
            }
        });
        jmRelatorio.add(jRelatUsuario);

        jmbMenuPrincipal.add(jmRelatorio);

        jmFuncionalidades.setText("Funcionalidades");

        jEmprestar.setText("Emprestar");
        jEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmprestarActionPerformed(evt);
            }
        });
        jmFuncionalidades.add(jEmprestar);

        jDevolver.setText("Devolver");
        jDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDevolverActionPerformed(evt);
            }
        });
        jmFuncionalidades.add(jDevolver);

        jmbMenuPrincipal.add(jmFuncionalidades);

        jmManutencao.setText("Manutenção");

        jmiManAutor.setText("Autor");
        jmiManAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManAutorActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManAutor);

        jmiManCategoria.setText("Categoria");
        jmiManCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManCategoriaActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManCategoria);

        jmiManCidade.setText("Cidade");
        jmiManCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManCidadeActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManCidade);

        jmiManDepartamento.setText("Departamento");
        jmiManDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManDepartamentoActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManDepartamento);

        jmiManEditora.setText("Editora");
        jmiManEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManEditoraActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManEditora);

        jmiManFornecedor.setText("Fornecedor");
        jmiManFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManFornecedorActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManFornecedor);

        jmiManFuncionario.setText("Funcionário");
        jmiManFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManFuncionarioActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManFuncionario);

        jmiManObra.setText("Livro");
        jmiManObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManObraActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManObra);

        jmiManUsuario.setText("Usuário");
        jmiManUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManUsuarioActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManUsuario);

        jmbMenuPrincipal.add(jmManutencao);

        jTrocarusuario.setText("Trocar usuário");
        jTrocarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrocarusuarioActionPerformed(evt);
            }
        });

        menuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuUsuario.setText("Usuário logoff");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });
        jTrocarusuario.add(menuUsuario);

        submenuAlterarSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        submenuAlterarSenha.setText("Alterar Senha");
        submenuAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuAlterarSenhaActionPerformed(evt);
            }
        });
        jTrocarusuario.add(submenuAlterarSenha);

        jmbMenuPrincipal.add(jTrocarusuario);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmbMenuPrincipal.add(jmSair);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadUsuario() throws SQLException{
        GUICadUsuario gcp = new GUICadUsuario();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
    private void abrirCadEditora() throws SQLException{
        GUICadEditora gcp = new GUICadEditora();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
    private void abrirCadFornecedor() throws SQLException{
        GUICadFornecedor gcp = new GUICadFornecedor();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
     private void abrirCadFuncionario() throws SQLException{
        GUICadFuncionario gcp = new GUICadFuncionario();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
     
     private void abrirCadObra() throws SQLException{
        GUICadLivro gcp = new GUICadLivro();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
     
    private void abrirCadDepartamento(){
        GUICadDepartamento gcp = new GUICadDepartamento();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
    private void abrirCadAutor() throws SQLException{
        GUICadAutor gcp = new GUICadAutor();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
      private void abrirCadCidade(){
        GUICadCidade gcp = new GUICadCidade();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
      
    private void abrirCadCategoria(){
    GUICadCategoria gcp = new GUICadCategoria();
    jAreaTrabalho.add(gcp);
    gcp.setVisible(true);
    }//fecha método
    
    private void abrirManUsuario() throws SQLException{
        GUIManutencaoUsuario gmp = new GUIManutencaoUsuario();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void abrirManEditora() throws SQLException{
        GUIManutencaoEditora gmp = new GUIManutencaoEditora();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void abrirManFornecedor() throws SQLException{
        GUIManutencaoFornecedor gmp = new GUIManutencaoFornecedor();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void abrirManFuncionario() throws SQLException{
        GUIManutencaoFuncionario gmp = new GUIManutencaoFuncionario();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void abrirManObra() throws SQLException{
        GUIManutencaoLivro gmp = new GUIManutencaoLivro();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void abrirManDepartamento(){
        GUIManutencaoDepartamento gmp = new GUIManutencaoDepartamento();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void abrirManAutor() throws SQLException{
        GUIManutencaoAutor gmp = new GUIManutencaoAutor();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
      private void abrirManCidade(){
        GUIManutencaoCidade gmp = new GUIManutencaoCidade();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
      
        private void abrirManCategoria(){
        GUIManutencaoCategoria gmp = new GUIManutencaoCategoria();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
     private void abrirEmprestar() throws SQLException{
        GUIEmprestar gmp = new GUIEmprestar();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
     
      private void abrirDevolver() throws SQLException{
        GUIDevolver gmp = new GUIDevolver();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
     }//fecha método   
     private void abrirAlterarSenha() throws SQLException{
        GUITelaAlterarSenha gmp = new GUITelaAlterarSenha();
        jAreaTrabalho.add(gmp);
        gmp.setVisible(true);
    }//fecha método
    
    private void jmCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadUsuarioActionPerformed
        GUICadUsuario frameGUICadUsuario = null;
        try {
            frameGUICadUsuario = new GUICadUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameGUICadUsuario.setVisible(true);
    }//GEN-LAST:event_jmCadUsuarioActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        this.fechar();
    }//GEN-LAST:event_jmSairMouseClicked
    private void fechar(){
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            this.dispose();
        }
    }
    private void jmiManUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManUsuarioActionPerformed
        try {
            abrirManUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiManUsuarioActionPerformed

    private void jmCadEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadEditoraActionPerformed
         GUICadEditora frameGUICadEditora = null;
        try {
            frameGUICadEditora = new GUICadEditora();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameGUICadEditora.setVisible(true);
    }//GEN-LAST:event_jmCadEditoraActionPerformed

    private void jmiManEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManEditoraActionPerformed
        try {
            abrirManEditora();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiManEditoraActionPerformed

    private void jRelatEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatEditoraActionPerformed
        RelatorioEditora frameRelatorioEditora = new RelatorioEditora();
        frameRelatorioEditora.setVisible(true);
    }//GEN-LAST:event_jRelatEditoraActionPerformed

    private void jRelatUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatUsuarioActionPerformed
        RelatorioUsuario frameRelatorioUsuario = new RelatorioUsuario();
        frameRelatorioUsuario.setVisible(true);
    }//GEN-LAST:event_jRelatUsuarioActionPerformed

    private void jmCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadFornecedorActionPerformed
         GUICadFornecedor frameGUICadFornecedor = null;
        try {
            frameGUICadFornecedor = new GUICadFornecedor();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameGUICadFornecedor.setVisible(true);
    }//GEN-LAST:event_jmCadFornecedorActionPerformed

    private void jmiManFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManFornecedorActionPerformed
        try {
            abrirManFornecedor();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiManFornecedorActionPerformed

    private void jjRelatFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatFornecedorActionPerformed
        RelatorioFornecedor frameRelatorioFornecedor = new RelatorioFornecedor();
        frameRelatorioFornecedor.setVisible(true);
    }//GEN-LAST:event_jjRelatFornecedorActionPerformed

    private void jmiManFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManFuncionarioActionPerformed
        try {
            abrirManFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiManFuncionarioActionPerformed

    private void jmCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadFuncionarioActionPerformed
        GUICadFuncionario frameGUICadFuncionario = null;
        try {
            frameGUICadFuncionario = new GUICadFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameGUICadFuncionario.setVisible(true);
    }//GEN-LAST:event_jmCadFuncionarioActionPerformed

    private void jjRelatFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatFuncionarioActionPerformed
        RelatorioFuncionario frameRelatorioFuncionario = new RelatorioFuncionario();
        frameRelatorioFuncionario.setVisible(true);
    }//GEN-LAST:event_jjRelatFuncionarioActionPerformed

    private void jmCadObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadObraActionPerformed
        GUICadLivro frameGUICadObra = null;
        try {
            frameGUICadObra = new GUICadLivro();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameGUICadObra.setVisible(true);
    }//GEN-LAST:event_jmCadObraActionPerformed

    private void jmiManObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManObraActionPerformed
        try {
            abrirManObra();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiManObraActionPerformed

    private void jmCadDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadDepartamentoActionPerformed
        GUICadDepartamento frameGUICadDepartamento = new GUICadDepartamento();
        frameGUICadDepartamento.setVisible(true);
    }//GEN-LAST:event_jmCadDepartamentoActionPerformed

    private void jmiManDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManDepartamentoActionPerformed
        abrirManDepartamento();
    }//GEN-LAST:event_jmiManDepartamentoActionPerformed

    private void jjRelatObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatObraActionPerformed
        RelatorioLivro frameRelatorioObra = new RelatorioLivro();
        frameRelatorioObra.setVisible(true);
    }//GEN-LAST:event_jjRelatObraActionPerformed

    private void jjRelatDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatDepartamentoActionPerformed
        RelatorioDepartamento frameRelatorioDepartamento = new RelatorioDepartamento();
        frameRelatorioDepartamento.setVisible(true);
    }//GEN-LAST:event_jjRelatDepartamentoActionPerformed

    private void jmCadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadAutorActionPerformed
        GUICadAutor frameGUICadAutor = null;
        try {
            frameGUICadAutor = new GUICadAutor();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        frameGUICadAutor.setVisible(true);
    }//GEN-LAST:event_jmCadAutorActionPerformed

    private void jmiManAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManAutorActionPerformed
        try {
            abrirManAutor();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiManAutorActionPerformed

    private void jjRelatAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatAutorActionPerformed
        RelatorioAutor frameRelatorioAutor = new RelatorioAutor();
        frameRelatorioAutor.setVisible(true);
    }//GEN-LAST:event_jjRelatAutorActionPerformed

    private void jEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmprestarActionPerformed
     GUIEmprestar frameGUIEmprestar = null;
        try {
            frameGUIEmprestar = new GUIEmprestar();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
     frameGUIEmprestar.setVisible(true);
    }//GEN-LAST:event_jEmprestarActionPerformed

    private void jDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDevolverActionPerformed
        GUIDevolver frameGUIDevolver = null;
        try {
            frameGUIDevolver = new GUIDevolver();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
     frameGUIDevolver.setVisible(true);
    }//GEN-LAST:event_jDevolverActionPerformed

    private void jjRelaEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelaEmprestimoActionPerformed
        RelatorioEmprestimo frameRelatorioEmprestimo = new RelatorioEmprestimo();
        frameRelatorioEmprestimo.setVisible(true);
    }//GEN-LAST:event_jjRelaEmprestimoActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        dispose();
        telalogin.setVisible(true);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void jTrocarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrocarusuarioActionPerformed

    }//GEN-LAST:event_jTrocarusuarioActionPerformed

    private void submenuAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuAlterarSenhaActionPerformed
        try {
            abrirAlterarSenha();
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submenuAlterarSenhaActionPerformed

    private void jmCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadCidadeActionPerformed
        GUICadCidade frameGUICadCidade = new GUICadCidade();
        frameGUICadCidade.setVisible(true);
    }//GEN-LAST:event_jmCadCidadeActionPerformed

    private void jjRelatCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatCidadeActionPerformed
        RelatorioCidade frameRelatorioCidade = new RelatorioCidade();
        frameRelatorioCidade.setVisible(true);
    }//GEN-LAST:event_jjRelatCidadeActionPerformed

    private void jmiManCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManCidadeActionPerformed
        abrirManCidade();
    }//GEN-LAST:event_jmiManCidadeActionPerformed

    private void jmCadCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadCategoriaActionPerformed
        GUICadCategoria frameGUICadCategoria = new GUICadCategoria();
        frameGUICadCategoria.setVisible(true);
    }//GEN-LAST:event_jmCadCategoriaActionPerformed

    private void jjRelatCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjRelatCategoriaActionPerformed
        RelatorioCategoria frameRelatorioCategoria = new RelatorioCategoria();
        frameRelatorioCategoria.setVisible(true);
    }//GEN-LAST:event_jjRelatCategoriaActionPerformed

    private void jmiManCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManCategoriaActionPerformed
        abrirManCategoria();
    }//GEN-LAST:event_jmiManCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuItem jDevolver;
    private javax.swing.JMenuItem jEmprestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jRelatEditora;
    private javax.swing.JMenuItem jRelatUsuario;
    private javax.swing.JMenu jTrocarusuario;
    private javax.swing.JMenuItem jjRelaEmprestimo;
    private javax.swing.JMenuItem jjRelatAutor;
    private javax.swing.JMenuItem jjRelatCategoria;
    private javax.swing.JMenuItem jjRelatCidade;
    private javax.swing.JMenuItem jjRelatDepartamento;
    private javax.swing.JMenuItem jjRelatFornecedor;
    private javax.swing.JMenuItem jjRelatFuncionario;
    private javax.swing.JMenuItem jjRelatObra;
    private javax.swing.JMenuItem jmCadAutor;
    private javax.swing.JMenuItem jmCadCategoria;
    private javax.swing.JMenuItem jmCadCidade;
    private javax.swing.JMenuItem jmCadDepartamento;
    private javax.swing.JMenuItem jmCadEditora;
    private javax.swing.JMenuItem jmCadFornecedor;
    private javax.swing.JMenuItem jmCadFuncionario;
    private javax.swing.JMenuItem jmCadObra;
    private javax.swing.JMenuItem jmCadUsuario;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmFuncionalidades;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiManAutor;
    private javax.swing.JMenuItem jmiManCategoria;
    private javax.swing.JMenuItem jmiManCidade;
    private javax.swing.JMenuItem jmiManDepartamento;
    private javax.swing.JMenuItem jmiManEditora;
    private javax.swing.JMenuItem jmiManFornecedor;
    private javax.swing.JMenuItem jmiManFuncionario;
    private javax.swing.JMenuItem jmiManObra;
    private javax.swing.JMenuItem jmiManUsuario;
    private javax.swing.JMenuItem menuUsuario;
    private javax.swing.JMenuItem submenuAlterarSenha;
    // End of variables declaration//GEN-END:variables
}
